
import { GoogleGenAI, Modality } from '@google/genai';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

type AspectRatio = '1:1' | '4:3' | '3:4' | '16:9' | '9:16';

export async function generateProductPhoto(
  base64ImageData: string, 
  mimeType: string,
  aspectRatio: AspectRatio
): Promise<string> {
  try {
    const model = 'gemini-2.5-flash-image';
    const prompt = `Transform this amateur product photo into a professional, high-quality product photograph with an aspect ratio of ${aspectRatio}.
    Place the product on a clean, neutral background (like a soft grey or white studio setting). 
    Enhance the lighting to highlight the product's details and textures, making it look appealing and realistic. 
    The final image should be suitable for an e-commerce website, catalog, or marketing materials. 
    Remove any distracting elements from the original background. The final image must strictly conform to the ${aspectRatio} aspect ratio.`;

    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64ImageData,
              mimeType: mimeType,
            },
          },
          {
            text: prompt,
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        const generatedMimeType = part.inlineData.mimeType;
        return `data:${generatedMimeType};base64,${base64ImageBytes}`;
      }
    }
    
    throw new Error("No image was generated by the API.");

  } catch (error) {
    console.error("Error generating product photo:", error);
    throw new Error("Failed to generate product photo. Please check your API key and try again.");
  }
}
